- .gitignore
- Services/JSON-RPC/CNN_ImageRecon_Service/run_image_recon_service.py
- Services/JSON-RPC/CNN_ObjectDetection/run_object_detection_service.py
- Services/gRPC/Basic_Template/run_basic_service.py
- Services/gRPC/CNN_ObjectDetection/run_object_detection_service.py
- Services/gRPC/CNN_VideoCaptioning/README.md
- Services/gRPC/CNN_VideoCaptioning/buildproto.sh
- Services/gRPC/CNN_VideoCaptioning/requirements.txt
- Services/gRPC/CNN_VideoCaptioning/run_video_cap_service.py
- Services/gRPC/CNN_VideoCaptioning/service/__init__.py
- Services/gRPC/CNN_VideoCaptioning/service/common.py
- Services/gRPC/CNN_VideoCaptioning/service/service_spec/video_cap.proto
- Services/gRPC/CNN_VideoCaptioning/service/utils/extract_features.py
- Services/gRPC/CNN_VideoCaptioning/service/utils/framefc7_text_to_hdf5_data.py
- Services/gRPC/CNN_VideoCaptioning/service/utils/get_s2vt.sh
- Services/gRPC/CNN_VideoCaptioning/service/utils/hdf5_npsequence_generator.py
- Services/gRPC/CNN_VideoCaptioning/service/utils/s2vt_captioner.py
- Services/gRPC/CNN_VideoCaptioning/service/utils/video_tools.py
- Services/gRPC/CNN_VideoCaptioning/service/video_cap_service.py
- Services/gRPC/CNN_VideoCaptioning/service/video_captioner.py
- Services/gRPC/CNN_VideoCaptioning/test_call_video_cap_service.py
- Services/gRPC/Meta_Services/CNN_ObjectDetection_ImageRecon/run_ObjectDetection_ImageRecon_service.py
- Services/gRPC/Meta_Services/README.md
- Using [S2VT](https://vsubhashini.github.io/s2vt.html) to provide caption of a video interval.
- Minor fixes at previous services.
> Integrate Video Captioning Service

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Services/gRPC/CNTK_ImageRecon/README.md
- Services/gRPC/I3D_VideoActionRecognition/README.md
- Services/gRPC/Meta_Services/ObjectDetection_ImageRecon/README.md
- Services/gRPC/S2VT_VideoCaptioning/README.md
- Services/gRPC/YOLOv3_ObjectDetection/README.md
- docs/index.html
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md](../../.github/CONTRIBUTING.md) document are followed
Fix some links.
> [Repo] Link to User's Guide Hub and wiki's CONTRIBUTING.md

- .circleci/config.yml
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md](https://github.com/singnet/wiki/blob/master/guidelines/CONTRIBUTING.md) document are followed
Change `$CIRCLE_USERNAME` -> `CIRCLE_PROJECT_USERNAME`
> [Repo] CircleCI test

- .circleci/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Services/gRPC/cntk-image-recon/Dockerfile
- Services/gRPC/cntk-image-recon/README.md
- Services/gRPC/i3d-video-action-recognition/Dockerfile
- Services/gRPC/i3d-video-action-recognition/README.md
- Services/gRPC/meta-services/object-detection-image-recon/Dockerfile
- Services/gRPC/meta-services/object-detection-image-recon/README.md
- Services/gRPC/s2vt-video-captioning/Dockerfile
- Services/gRPC/s2vt-video-captioning/README.md
- Services/gRPC/yolov3-object-detection/Dockerfile
- Services/gRPC/yolov3-object-detection/README.md
- docs/users_guide/cntk-image-recon.md
- docs/users_guide/i3d-video-action-recognition.md
- docs/users_guide/object-detection-image-recon.md
- docs/users_guide/s2vt-video-captioning.md
- docs/users_guide/yolov3-object-detection.md
-   [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md](https://github.com/singnet/wiki/blob/master/guidelines/CONTRIBUTING.md) document are followed
- Daemon flags `*_NAME` to `*_ID`.
- CircleCI with optional `-v` flag.
> New Daemon and CircleCI configs

- .circleci/config.yml
- README.md
- Services/gRPC/zeta36-chess-alpha-zero/Dockerfile
- Services/gRPC/zeta36-chess-alpha-zero/README.md
- Services/gRPC/zeta36-chess-alpha-zero/buildproto.sh
- Services/gRPC/zeta36-chess-alpha-zero/requirements.txt
- Services/gRPC/zeta36-chess-alpha-zero/run_alpha_zero_service.py
- Services/gRPC/zeta36-chess-alpha-zero/service/__init__.py
- Services/gRPC/zeta36-chess-alpha-zero/service/alpha_zero.py
- Services/gRPC/zeta36-chess-alpha-zero/service/alpha_zero_service.py
- Services/gRPC/zeta36-chess-alpha-zero/service/common.py
- Services/gRPC/zeta36-chess-alpha-zero/service/service_spec/alpha_zero.proto
- Services/gRPC/zeta36-chess-alpha-zero/service/tf_session.py
- Services/gRPC/zeta36-chess-alpha-zero/test_alpha_zero_service.py
- docs/index.html
- docs/users_guide/zeta36-chess-alpha-zero.html
- docs/users_guide/zeta36-chess-alpha-zero.md
- Add the service `zeta36-chess-alpha-zero`.
- Improve the `config.yml`, separated workflows for each service.
> [chess-alpha-zero] Add service

- .circleci/config.yml
- Services/gRPC/cntk-image-recon/Dockerfile
- Services/gRPC/cntk-image-recon/README.md
- Services/gRPC/cntk-image-recon/run_image_recon_service.py
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.kovan.json
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.ropsten.json
- Services/gRPC/i3d-video-action-recognition/Dockerfile
- Services/gRPC/i3d-video-action-recognition/README.md
- Services/gRPC/i3d-video-action-recognition/run_video_action_recon_service.py
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.kovan.json
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.ropsten.json
- Services/gRPC/s2vt-video-captioning/Dockerfile
- Services/gRPC/s2vt-video-captioning/README.md
- Services/gRPC/s2vt-video-captioning/run_video_cap_service.py
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.kovan.json
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.ropsten.json
- Services/gRPC/yolov3-object-detection/Dockerfile
- Services/gRPC/yolov3-object-detection/README.md
- Services/gRPC/yolov3-object-detection/run_object_detection_service.py
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.kovan.json
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.ropsten.json
- Services/gRPC/zeta36-chess-alpha-zero/Dockerfile
- Services/gRPC/zeta36-chess-alpha-zero/README.md
- Services/gRPC/zeta36-chess-alpha-zero/run_alpha_zero_service.py
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.kovan.json
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.ropsten.json
- Update `snet-daemon` to latest version `v0.1.5`.
- New `config.yml` to deploy services onto Kovan & Ropsten.
- Move `snetd.*.json` to specific folder.
> [ropsten] Deploy onto Kovan and Ropsten.

- .circleci/config.yml
- .gitignore
- New `config.yml` with build&test steps separated from deploy steps.
- Add `/etcd` to `.gitignore`.
> [circleCI] Deploy in a separated job.

- Services/gRPC/cntk-image-recon/README.md
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.kovan.json
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.ropsten.json
- Services/gRPC/i3d-video-action-recognition/README.md
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.kovan.json
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.ropsten.json
- Services/gRPC/s2vt-video-captioning/README.md
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.kovan.json
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.ropsten.json
- Services/gRPC/yolov3-object-detection/README.md
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.kovan.json
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.ropsten.json
- Services/gRPC/zeta36-chess-alpha-zero/README.md
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.kovan.json
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.ropsten.json
- Change `https://` to `http://`.
> [daemon] https -> http.

- Services/gRPC/cntk-image-recon/Dockerfile
- Services/gRPC/cntk-image-recon/README.md
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.kovan.json
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.ropsten.json
- Services/gRPC/i3d-video-action-recognition/Dockerfile
- Services/gRPC/i3d-video-action-recognition/README.md
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.kovan.json
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.ropsten.json
- Services/gRPC/s2vt-video-captioning/Dockerfile
- Services/gRPC/s2vt-video-captioning/README.md
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.kovan.json
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.ropsten.json
- Services/gRPC/yolov3-object-detection/Dockerfile
- Services/gRPC/yolov3-object-detection/README.md
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.kovan.json
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.ropsten.json
- Services/gRPC/zeta36-chess-alpha-zero/Dockerfile
- Services/gRPC/zeta36-chess-alpha-zero/README.md
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.kovan.json
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.ropsten.json
- Remove `http://` from Daemon's config.
- Update to `v0.1.6`
> [services] Remove http from DAEMON_END_POINT (v0.1.6).

- Services/gRPC/cntk-image-recon/README.md
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.kovan.json
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.ropsten.json
- Services/gRPC/i3d-video-action-recognition/README.md
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.kovan.json
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.ropsten.json
- Services/gRPC/s2vt-video-captioning/README.md
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.kovan.json
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.ropsten.json
- Services/gRPC/yolov3-object-detection/README.md
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.kovan.json
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.ropsten.json
- Services/gRPC/zeta36-chess-alpha-zero/README.md
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.kovan.json
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.ropsten.json
- Change `DAEMON_HOST` to `0.0.0.0`
> [services] DAEMON_HOST at 0.0.0.0 (v0.1.6).

- .circleci/config.yml
- Add production tag to Docker container's name (`PROD_*`).
> [circleci] Production TAG.

- .circleci/config.yml
- Services/gRPC/places365-scene-recognition/Dockerfile
- Services/gRPC/places365-scene-recognition/run_scene_recognition_service.py
- Services/gRPC/places365-scene-recognition/service/__init__.py
- Services/gRPC/places365-scene-recognition/snetd_configs/snetd.kovan.json
- Services/gRPC/places365-scene-recognition/snetd_configs/snetd.ropsten.json
- Services/gRPC/places365-scene-recognition/test_scene_recognition_service.py
> Updating Scene Recognition Service

- .circleci/config.yml
- Services/gRPC/places365-scene-recognition/service/scene_recognition.py
- Services/gRPC/places365-scene-recognition/service/scene_recognition_service.py
- Services/gRPC/places365-scene-recognition/service/serviceUtils.py
- docs/users_guide/places365-scene-recognition.md
Adding support for:
- PNG images through URLs;
- base64 images with header (i.e.: "data:image/png;base64,[actual data]");
- "encrypted" image URLs (i.e.: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaG-fKuByFxfXLxh84lADPDOxipjDRR9geZdv9HnW703MqONDzzw" ). Being treated as ".jpg".
> Fixing Scene Recognition

- .circleci/config.yml
- Services/gRPC/cntk-image-recon/Dockerfile
- Services/gRPC/cntk-image-recon/README.md
- Services/gRPC/cntk-image-recon/snetd_configs/snetd.mainnet.json
- Services/gRPC/i3d-video-action-recognition/Dockerfile
- Services/gRPC/i3d-video-action-recognition/README.md
- Services/gRPC/i3d-video-action-recognition/snetd_configs/snetd.mainnet.json
- Services/gRPC/s2vt-video-captioning/Dockerfile
- Services/gRPC/s2vt-video-captioning/README.md
- Services/gRPC/s2vt-video-captioning/snetd_configs/snetd.mainnet.json
- Services/gRPC/yolov3-object-detection/Dockerfile
- Services/gRPC/yolov3-object-detection/README.md
- Services/gRPC/yolov3-object-detection/snetd_configs/snetd.mainnet.json
- Services/gRPC/zeta36-chess-alpha-zero/Dockerfile
- Services/gRPC/zeta36-chess-alpha-zero/README.md
- Services/gRPC/zeta36-chess-alpha-zero/snetd_configs/snetd.mainnet.json
- Daemon with Mainnet configs.
- New Daemon `v0.1.7`.
- Removes Kovan's references.
> [mainnet] Mainnet deploy and Daemon v0.1.7.

- .circleci/config.yml
- Fix port mapping of Places365.
> [Fix] Places365's CircleCI.

- .circleci/config.yml
- services/cntk-image-recon/Dockerfile
- services/i3d-video-action-recognition/Dockerfile
- services/i3d-video-action-recognition/test_video_action_recon_service.py
- services/places365-scene-recognition/Dockerfile
- services/places365-scene-recognition/snetd_configs/snetd.mainnet.json
- services/s2vt-video-captioning/Dockerfile
- services/s2vt-video-captioning/test_video_cap_service.py
- services/yolov3-object-detection/Dockerfile
- services/zeta36-chess-alpha-zero/Dockerfile
- New Daemon (v0.1.8).
- Using storage link for auto testing (S2VT and I3D).
- Places365 on Ropsten and Mainnet.
> Daemon v0.1.8

- .circleci/config.yml
- services/cntk-image-recon/Dockerfile
- services/i3d-video-action-recognition/Dockerfile
- services/places365-scene-recognition/Dockerfile
- services/s2vt-video-captioning/Dockerfile
- services/yolov3-object-detection/Dockerfile
- services/zeta36-chess-alpha-zero/Dockerfile
> Updating daemon downloading script for all services

- .circleci/config.yml
- services/siggraph-colorization/snetd_configs/snetd.mainnet
> [Colorize] New mainnet port.

- docs/index.html
- docs/users_guide/pneumonia-diagnosis.md
- services/pneumonia-diagnosis/README.md
- services/pneumonia-diagnosis/service/pneumonia_diagnosis.py
- services/pneumonia-diagnosis/service/service_spec/pneumonia_diagnosis.proto
- Changed `bool` to `string` in .proto
- README fixes.
> Pneumonia diagnosis

- .circleci/config.yml
> [ci] Certificates must now be available on every build/run.

- .circleci/check_md5.sh
- .circleci/config.yml
> [repo] check_md5 getting only the MD5 hash.

- README.md
> Forcing CI

- README.md
- docs/users_guide/real-time-voice-cloning.md
- services/real-time-voice-cloning/README.md
> Readme fixes/additions.

- .circleci/config.yml
- README.md
- docs/index.html
- docs/users_guide/sound-spleeter.html
- docs/users_guide/sound-spleeter.md
- services/sound-spleeter/Dockerfile
- services/sound-spleeter/README.md
- services/sound-spleeter/buildproto.sh
- services/sound-spleeter/requirements.txt
- services/sound-spleeter/run_sound_spleeter_service.py
- services/sound-spleeter/service/__init__.py
- services/sound-spleeter/service/common.py
- services/sound-spleeter/service/service_spec/sound_spleeter.proto
- services/sound-spleeter/service/sound_spleeter.py
- services/sound-spleeter/service/sound_spleeter_service.py
- services/sound-spleeter/snetd_configs/snetd.mainnet
- services/sound-spleeter/snetd_configs/snetd.ropsten.json
- services/sound-spleeter/test_sound_spleeter_service.py
- Adding new service: `sound-spleeter`
> [sound-spleeter] Adding service.

- docs/users_guide/sound-spleeter.html
- Fix at `docs/users_guide/sound-spleeter.html`
> [sound-spleeter] Fix Users Guide.

- .circleci/config.yml
- services/cntk-image-recon/Dockerfile
- services/deepfakes-faceswap/Dockerfile
- services/deepfakes-faceswap/requirements.txt
- services/i3d-video-action-recognition/Dockerfile
- services/i3d-video-action-recognition/requirements.txt
- services/places365-scene-recognition/Dockerfile
- services/pneumonia-diagnosis/Dockerfile
- services/pneumonia-diagnosis/requirements.txt
- services/real-time-voice-cloning/Dockerfile
- services/real-time-voice-cloning/requirements.txt
- services/s2vt-video-captioning/Dockerfile
- services/siggraph-colorization/Dockerfile
- services/sound-spleeter/Dockerfile
- services/sound-spleeter/service/sound_spleeter.py
- services/yolov3-object-detection/Dockerfile
- services/zeta36-chess-alpha-zero/Dockerfile
- services/zeta36-chess-alpha-zero/requirements.txt
> [ci] Getting Daemon PK in an elegant way.

- services/s2vt-video-captioning/service/service_spec/video_cap.proto
- services/s2vt-video-captioning/service/video_cap_service.py
- services/s2vt-video-captioning/service/video_captioner.py
- services/s2vt-video-captioning/test_video_cap_service.py
> [s2vt-video-captioning] Changing protobuf input type string to float.

- .circleci/config.yml
- services/cntk-image-recon/run_image_recon_service.py
- services/deepfakes-faceswap/run_deepfakes_faceswap_service.py
- services/i3d-video-action-recognition/run_video_action_recon_service.py
- services/places365-scene-recognition/run_scene_recognition_service.py
- services/pneumonia-diagnosis/run_pneumonia_diagnosis_service.py
- services/real-time-voice-cloning/run_voice_cloning_service.py
- services/s2vt-video-captioning/run_video_cap_service.py
- services/siggraph-colorization/run_colorize_service.py
- services/sound-spleeter/run_sound_spleeter_service.py
- services/yolov3-object-detection/run_object_detection_service.py
- services/zeta36-chess-alpha-zero/run_alpha_zero_service.py
Adding the Infura API key to the CircleCI deployment as an environment variable.
> Infura key

- .circleci/config.yml
- services/i3d-video-action-recognition/service/video_action_recon.py
- `i3d-video-action-recognition` new response format:
```
[92.60%] playing guitar
[06.91%] strumming guitar
[00.34%] tapping guitar
[00.16%] playing bass guitar
[00.00%] busking
```
- CI improvements:
- `git fetch` and `git checkout` to make sure that the code is updated with the branch.
- using `bash -c "COMMAND"` on `docker run ...` for the sake of simplicity.
> Better response format for i3d and CI improvements

- .circleci/config.yml
Using `git pull` before running service to make sure the branch is updated.
> [ci] Adding back the git pull.

- services/deepfakes-faceswap/requirements.txt
- services/i3d-video-action-recognition/requirements.txt
- services/pneumonia-diagnosis/requirements.txt
- services/real-time-voice-cloning/requirements.txt
- services/zeta36-chess-alpha-zero/Dockerfile
- services/zeta36-chess-alpha-zero/requirements.txt
> [dep] Bumping TF version.

- .circleci/config.yml
- services/cntk-image-recon/Dockerfile
- services/deepfakes-faceswap/Dockerfile
- services/i3d-video-action-recognition/Dockerfile
- services/places365-scene-recognition/Dockerfile
- services/pneumonia-diagnosis/Dockerfile
- services/real-time-voice-cloning/Dockerfile
- services/s2vt-video-captioning/Dockerfile
- services/siggraph-colorization/Dockerfile
- services/sound-spleeter/Dockerfile
- services/yolov3-object-detection/Dockerfile
- services/zeta36-chess-alpha-zero/Dockerfile
The Daemon's version can be set by:
- Github API (from releases)
- CircleCI env vars (`CI_SNETD_VERSION`)
- Dockerfile (hardcoded ARG snetd_version)
> Adding snetd_version as Dockerfile ARG.

- services/cntk-image-recon/Dockerfile
- services/cntk-image-recon/service/image_recon_service.py
- services/deepfakes-faceswap/Dockerfile
- services/deepfakes-faceswap/requirements.txt
- services/i3d-video-action-recognition/Dockerfile
- services/i3d-video-action-recognition/requirements.txt
- services/i3d-video-action-recognition/service/video_action_recon.py
- services/i3d-video-action-recognition/service/video_action_recon_service.py
- services/places365-scene-recognition/Dockerfile
- services/pneumonia-diagnosis/Dockerfile
- services/real-time-voice-cloning/Dockerfile
- services/s2vt-video-captioning/Dockerfile
- services/s2vt-video-captioning/service/utils/video_tools.py
- services/siggraph-colorization/Dockerfile
- services/sound-spleeter/Dockerfile
- services/yolov3-object-detection/Dockerfile
- services/yolov3-object-detection/service/object_detection_service.py
- services/zeta36-chess-alpha-zero/Dockerfile
- services/zeta36-chess-alpha-zero/service/alpha_zero_service.py
Using `multiprocessing` module to avoid memory leak.
> Multiprocess

- .circleci/config.yml
- services/cntk-image-recon/run_image_recon_service.py
- services/deepfakes-faceswap/run_deepfakes_faceswap_service.py
- services/i3d-video-action-recognition/run_video_action_recon_service.py
- services/places365-scene-recognition/run_scene_recognition_service.py
- services/pneumonia-diagnosis/run_pneumonia_diagnosis_service.py
- services/real-time-voice-cloning/run_voice_cloning_service.py
- services/s2vt-video-captioning/run_video_cap_service.py
- services/siggraph-colorization/run_colorize_service.py
- services/sound-spleeter/run_sound_spleeter_service.py
- services/yolov3-object-detection/run_object_detection_service.py
- services/zeta36-chess-alpha-zero/run_alpha_zero_service.py
- Removing old Daemon config keys.
> [repo] Updating the Daemon config keys.

- .circleci/config.yml
- Using Orb `2.2.0` that only triggers tests after all builds.
> [orb] Test step with requires.

- services/sound-spleeter/requirements.txt
- services/sound-spleeter/service/sound_spleeter.py
Using `pydub` to reduce the response size (audio files).
> [sound-spleeter] Using pydub to convert wav -> mp3.

- .circleci/config.yml
- services/cntk-image-recon/service/image_recon_service.py
- services/deoldify-colorizer/service/colorization_service.py
- services/i3d-video-action-recognition/service/video_action_recon_service.py
- services/places365-scene-recognition/service/scene_recognition_service.py
- services/real-time-voice-cloning/run_voice_cloning_service.py
- services/real-time-voice-cloning/service/voice_cloning.py
- services/real-time-voice-cloning/service/voice_cloning_service.py
- services/s2vt-video-captioning/service/video_cap_service.py
- services/sound-spleeter/service/sound_spleeter.py
- services/sound-spleeter/service/sound_spleeter_service.py
- services/yolov3-object-detection/service/object_detection_service.py
Better usage of `multiprocessing` on all services!
> [repo] Releasing all GPU memory.

- services/i3d-video-action-recognition/service/video_action_recon.py
> [i3d] Reducing TF GPU memory usage.

- docs/users_guide/sound-spleeter.md
- services/i3d-video-action-recognition/test_service.py
- services/s2vt-video-captioning/test_service.py
- services/sound-spleeter/Dockerfile
- services/sound-spleeter/README.md
- services/sound-spleeter/requirements.txt
- services/sound-spleeter/test_service.py
- utils/get_cntk_models.sh
- utils/get_colorize_model.sh
- utils/get_voice_model.sh
- utils/get_yolov3.sh
- Adding GPU to the `sound-spleeter` service.
- Adding HTTPS to the storage links.
> [sound-spleeter] Using GPU

- services/cntk-image-recon/requirements.txt
- services/deepfakes-faceswap/requirements.txt
- services/deoldify-colorizer/requirements.txt
- services/i3d-video-action-recognition/requirements.txt
- services/places365-scene-recognition/requirements.txt
- services/pneumonia-diagnosis/requirements.txt
- services/real-time-voice-cloning/requirements.txt
- services/s2vt-video-captioning/requirements.txt
- services/sound-spleeter/requirements.txt
- services/yolov3-object-detection/requirements.txt
- services/zeta36-chess-alpha-zero/requirements.txt
> Freezing gRPC versions.

- services/cntk-image-recon/requirements.txt
- services/deepfakes-faceswap/requirements.txt
- services/i3d-video-action-recognition/requirements.txt
- services/places365-scene-recognition/requirements.txt
- services/pneumonia-diagnosis/requirements.txt
- services/real-time-voice-cloning/requirements.txt
- services/zeta36-chess-alpha-zero/requirements.txt
- utils/requirements.txt
Bumping the TF and Pillow versions.
> [repo] Updating TF and Pillow versions.

- services/cntk-image-recon/Dockerfile
- services/cntk-image-recon/run_service.py
- services/deepfakes-faceswap/run_service.py
- services/deoldify-colorizer/run_service.py
- services/i3d-video-action-recognition/run_service.py
- services/places365-scene-recognition/run_service.py
- services/pneumonia-diagnosis/run_service.py
- services/real-time-voice-cloning/run_service.py
- services/s2vt-video-captioning/run_service.py
- services/sound-spleeter/run_service.py
- services/yolov3-object-detection/run_service.py
- services/zeta36-chess-alpha-zero/run_service.py
> [snetd] metering_enabled: true

- services/sound-spleeter/service/sound_spleeter.py
- services/sound-spleeter/service/sound_spleeter_service.py
> Sound multiprocs

- services/sound-spleeter/run_service.py
> Increase default maximum message size to 128Mb

- services/deoldify-colorizer/Dockerfile
- services/deoldify-colorizer/requirements.txt
- services/deoldify-colorizer/test_service.py
> [deoldify-colorizer] Freezing OpenCV version.

- services/i3d-video-action-recognition/requirements.txt
- services/s2vt-video-captioning/requirements.txt
> Bumping youtube_dl versions.
